name: 15-minute-cron
on:
  schedule:
    - cron: '0 10 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://my-projects-dashboard.vercel.app/api/stats' \
          --header 'Authorization: Bearer ${{ secrets.APP_API_KEY }}'
